#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL (Vision)
#
# @type Quadrotor Wide
#

. ${R}etc/init.d/airframes/4060_dji_matrice_100


param set MAV_TYPE 2
#param set SYS_AUTOSTART 4060
# param set SYS_AUTOSTART 4060 DJI
param set SYS_RESTART_TYPE 0
param set SYS_MC_EST_GROUP 1


param set BAT_N_CELLS 6
param set CAL_GYRO0_ID 2293768
param set CAL_ACC0_ID 1376264
param set CAL_ACC1_ID 1310728
param set CAL_MAG0_ID 196616
param set CAL_GYRO0_XOFF 0.01
param set CAL_ACC0_XOFF 0.01
param set CAL_ACC0_YOFF -0.01
param set CAL_ACC0_ZOFF 0.01
param set CAL_ACC0_XSCALE 1.01
param set CAL_ACC0_YSCALE 1.01
param set CAL_ACC0_ZSCALE 1.01
param set CAL_ACC1_XOFF 0.01
param set CAL_MAG0_XOFF 0.01
param set SENS_BOARD_ROT 0
param set SENS_BOARD_X_OFF 0.000001
param set COM_RC_IN_MODE 1
param set NAV_DLL_ACT 2
#param set COM_DISARM_LAND -1
param set COM_DISARM_LAND 0
param set NAV_ACC_RAD 2.0
param set COM_OF_LOSS_T 5
param set COM_OBL_ACT 2
param set COM_OBL_RC_ACT 0
param set RTL_RETURN_ALT 30.0
param set RTL_DESCEND_ALT 5.0
param set RTL_LAND_DELAY 5
param set MIS_TAKEOFF_ALT 2.5
param set MC_ROLL_P 6.5
param set MC_ROLLRATE_P 0.05
param set MC_ROLLRATE_I 0.05
param set MC_ROLLRATE_D 0.001
param set MC_PITCH_P 6.5
param set MC_PITCHRATE_P 0.05
param set MC_PITCHRATE_I 0.05
param set MC_PITCHRATE_D 0.001
param set MC_YAWRATE_P 0.2
param set MC_YAWRATE_I 0.0
param set MC_YAWRATE_D 0.0
param set MPC_HOLD_MAX_Z 2.0
param set EKF2_GBIAS_INIT 0.01
param set EKF2_ANGERR_INIT 0.01

### GPS only mode ###
#param set LPE_FUSION 145
#param set ATT_EXT_HDG_M 0
### ---End--- ###
### MOCAP only mode ###
param set LPE_FUSION 0
param set ATT_EXT_HDG_M 2
### ---End--- ###

# 11110111 no vis yaw (1 << 3)
#param set SITL_UDP_PRT 14560
param set LPE_PN_V 0.7

param set MPC_XY_P 1.3
param set MPC_Z_P 1.30

# Old parameters
#param set MPC_XY_VEL_P 0.13
#param set MPC_Z_VEL_D 0.030
#param set MPC_Z_VEL_I 0.010
#param set MPC_Z_VEL_P 0.10
#param set PWM_MIN 1200
#param set PWM_MAX 1950
